controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    defaults:
        schemes: [https]

homepage:
    path: /
    controller: App\Controller\PagesController::index