name: NodeJS with Webpack

on:
 push:
  branches: ['main']
 pull_request:
  branches: ['main']

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [16.x]

  steps:
   - uses: actions/checkout@v3

   - name: Use Node.js ${{ matrix.node-version }}
     uses: borales/actions-yarn@v4
     with:
      node-version: ${{ matrix.node-version }}

   - name: Build
     run: |
      npm install --force
      npm run build
